services:
  catering:
    image: eko1394/catering:1.0.0
    ports:
      - 8080:8080
    depends_on:
      - catering-db
    networks:
      - catering-net    
    restart: on-failure
    healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:8080/swagger"]
        interval: 15s
        timeout: 10s
        retries: 3
        start_period: 45s
  # catering-migration:
  #   image: eko1394/catering-migration:1.0.0
  #   depends_on:
  #     - catering-db
  #   networks:
  #     - catering-net
  catering-db:
    image: eko1394/catering-db:1.0.0
    ports:
      - 1433:1433
    volumes:
      - catering-db-data:/var/opt/mssql
    networks:
      - catering-net
    restart: on-failure
    environment:
      SA_PASSWORD: "${SA_PASSWORD}"
    healthcheck:
      test: ["CMD", "/opt/mssql-tools/bin/sqlcmd", "-U", "sa", "-P" , "${SA_PASSWORD}", "-Q", "select 1"]
      interval: 30s
      timeout: 10s
      retries: 3
  rabbitmq:
    image: rabbitmq:3.13.7-management
    container_name: rabbitmq
    ports:
      - "5672:5672"  # Puerto AMQP
      - "15672:15672" # UI de gestión
    volumes:
      - ./.rabbitmq/definitions.json:/etc/rabbitmq/definitions.json
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
      RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS: "-rabbitmq_management load_definitions \"/etc/rabbitmq/definitions.json\""
    networks:
      - catering-net #actualizar network
    healthcheck:
      test: ["CMD-SHELL", "rabbitmq-diagnostics -q ping"]
      interval: 5s
      timeout: 3s
      retries: 5
volumes:
  catering-db-data:
networks:
  catering-net: