# Use the official Microsoft SQL Server image
FROM mcr.microsoft.com/mssql/server:2022-latest AS base

# Set environment variables
ENV ACCEPT_EULA=Y
ENV SA_PASSWORD=${SA_PASSWORD}
ENV MSSQL_PID=Express
ENV MSSQL_TCP_PORT=1433

# Expose the SQL Server port
EXPOSE 1433

COPY Catering.Infrastructure/Migrations_scripts/creation_script.sql /scripts/.
COPY Catering.Infrastructure/Migrations_scripts/migration_script.sql /scripts/.
COPY Catering.Infrastructure/Migrations_scripts/AddRabbitMQ_script.sql /scripts/.
COPY Catering.Infrastructure/Migrations_scripts/AddRecetas_script.sql /scripts/.
COPY Catering.Infrastructure/Migrations_scripts/AddContratoInOrdenFinalizada_script.sql /scripts/.

# Start SQL Server and execute the migration script
#CMD /opt/mssql/bin/sqlservr & sleep 30 && /opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P Password123*** -d tempdb -i /migration_script.sql & wait
CMD /opt/mssql/bin/sqlservr & sleep 45 && /opt/mssql-tools18/bin/sqlcmd -U sa -P ${SA_PASSWORD} -C -e -i /scripts/creation_script.sql && /opt/mssql-tools18/bin/sqlcmd -U sa -P ${SA_PASSWORD} -C -e -i /scripts/migration_script.sql && /opt/mssql-tools18/bin/sqlcmd -U sa -P ${SA_PASSWORD} -C -e -i /scripts/AddRabbitMQ_script.sql && /opt/mssql-tools18/bin/sqlcmd -U sa -P ${SA_PASSWORD} -C -e -i /scripts/AddRecetas_script.sql && /opt/mssql-tools18/bin/sqlcmd -U sa -P ${SA_PASSWORD} -C -e -i /scripts/AddContratoInOrdenFinalizada_script.sql & sleep infinity

    